#
# Copyright 2013-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

name: C/C++ CI
on: push
jobs:
  x86_ubuntu_build:
    name: Build on x86
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04]
        compiler: [gcc]
    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: |
        sudo docker/scripts/install_dependencies.sh
    - name: Build srsRAN Project on x86 ${{ matrix.os }} with compiler ${{ matrix.compiler }}
      run: |
        docker/scripts/builder.sh -c ${{ matrix.compiler }} -m "-j$(nproc)" .
    - name: Run unit tests
      run: |
        cd build && ctest -j$(nproc) --schedule-random --output-on-failure
