#
# Copyright 2013-2025 Software Radio Systems Limited
#
# By using this file, you agree to the terms and conditions set
# forth in the LICENSE file which can be found at the top level of
# the distribution.
#

db_uri: mongodb://${MONGODB_IP}/open5gs

logger:

test:
  serving:
    - plmn_id:
        mcc: 001
        mnc: 01

global:
  parameter:
    no_ipv6: true
    # no_nrf: true
    # no_scp: true
    no_sepp: true
    # no_amf: true
    # no_smf: true
    # no_upf: true
    # no_ausf: true
    # no_udm: true
    # no_pcf: true
    # no_nssf: true
    # no_bsf: true
    # no_udr: true
    # no_mme: true
    # no_sgwc: true
    # no_sgwu: true
    # no_pcrf: true
    # no_hss: true

mme:
  freeDiameter:
    identity: mme.localdomain
    realm: localdomain
    listen_on: 10.53.1.2
    no_fwd: true
    load_extension:
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dbg_msg_dumps.fdx"
        conf: 0x8888
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_rfc5777.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_mip6i.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nasreq.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nas_mipv6.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca_3gpp.fdx"
    connect:
      - identity: hss.localdomain
        address: 10.53.1.8

  s1ap:
    server:
      - address: ${OPEN5GS_IP}
  gtpc:
    server:
      - address: ${OPEN5GS_IP}
    client:
      sgwc:
        - address: 10.53.1.3
      smf:
        - address: 10.53.1.4
  gummei:
    - plmn_id:
        mcc: 001
        mnc: 01
      mme_gid: 2
      mme_code: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7
  security:
    integrity_order: [EIA2, EIA1, EIA0]
    ciphering_order: [EEA0, EEA1, EEA2]
  network_name:
    full: ${NETWORK_NAME_FULL}
    short: ${NETWORK_NAME_SHORT}
  time:
    t3412:
      value: 540

sgwc:
  gtpc:
    server:
      - address: 10.53.1.3
  pfcp:
    server:
      - address: 10.53.1.3
    client:
      sgwu:
        - address: 10.53.1.6

smf:
  sbi:
    server:
      - address: 10.53.1.4
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777
  pfcp:
    server:
      - address: 10.53.1.4
    client:
      upf:
        - address: 10.53.1.7
  gtpc:
    server:
      - address: 10.53.1.4
  gtpu:
    server:
      - address: 10.53.1.4
  metrics:
    server:
      - address: 10.53.1.4
        port: 9090
  session:
    - subnet: ${UE_GATEWAY_IP}
    - subnet: 10.45.2.0/24      # Ajout pour IMS
      qos:
        index: 1                # QCI 1 pour la Latino voice QoS Flow pour VoNR
        arp:
          priority_level: 1
          pre_emption_capability: enabled
          pre_emption_vulnerability: enabled
  dns:
    - 8.8.8.8
    - 8.8.4.4
    - 10.53.1.100
  mtu: 1400
  freeDiameter:
    identity: smf.localdomain
    realm: localdomain
    listen_on: 10.53.1.4
    no_fwd: true
    load_extension:
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dbg_msg_dumps.fdx"
        conf: 0x8888
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_rfc5777.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_mip6i.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nasreq.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nas_mipv6.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca_3gpp.fdx"
    connect:
      - identity: pcrf.localdomain
        address: 10.53.1.9
  security_indication:
    # Uncomment to enable UP integrity protection
    #integrity_protection_indication: preferred
    #confidentiality_protection_indication: preferred
  session:
    - subnet: ${UE_GATEWAY_IP}  # Déjà présent
    - subnet: 10.45.2.0/24      # Ajouter une plage pour IMS
      qos:
        index: 1                # QCI 1 pour la voix
        arp:
          priority_level: 1
          pre_emption_capability: enabled
          pre_emption_vulnerability: enabled

amf:
  sbi:
    server:
      - address: 10.53.1.5
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777
  ngap:
    server:
      - address: ${OPEN5GS_IP}
  guami:
    - plmn_id:
        mcc: 001
        mnc: 01
      amf_id:
        region: 2
        set: 1
  tai:
    - plmn_id:
        mcc: 001
        mnc: 01
      tac: 7
  plmn_support:
    - plmn_id:
        mcc: 001
        mnc: 01
      s_nssai:
        - sst: 1
        - sst: 2             # Ajouter slice pour IMS
          sd: 1
  security:
    integrity_order: [NIA2, NIA1, NIA0]
    ciphering_order: [NEA0, NEA1, NEA2]
  network_name:
    full: ${NETWORK_NAME_FULL}
    short: ${NETWORK_NAME_SHORT}
  amf_name: open5gs-amf0
  time:
    t3512:
      value: 540 # 9 minutes * 60 = 540 seconds

sgwu:
  pfcp:
    server:
      - address: 10.53.1.6
  gtpu:
    server:
      - address: 10.53.1.6

upf:
  pfcp:
    server:
      - address: 10.53.1.7
  gtpu:
    server:
      - address: ${OPEN5GS_IP}
        advertise: ${UPF_ADVERTISE_IP}
  session:
    - subnet: ${UE_GATEWAY_IP}

hss:
  freeDiameter:
    identity: hss.localdomain
    realm: localdomain
    listen_on: 10.53.1.8
    no_fwd: true
    load_extension:
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dbg_msg_dumps.fdx"
        conf: 0x8888
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_rfc5777.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_mip6i.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nasreq.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nas_mipv6.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca_3gpp.fdx"
    connect:
      - identity: mme.localdomain
        address: 10.53.1.2
pcrf:
  freeDiameter:
    identity: pcrf.localdomain
    realm: localdomain
    listen_on: 10.53.1.9
    no_fwd: true
    load_extension:
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dbg_msg_dumps.fdx"
        conf: 0x8888
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_rfc5777.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_mip6i.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nasreq.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_nas_mipv6.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca.fdx"
      - module: "/open5gs/install/lib/${INSTALL_ARCH}/freeDiameter/dict_dcca_3gpp.fdx"
    connect:
      - identity: smf.localdomain
        address: 10.53.1.4

nrf:
  sbi:
    server:
      - address: 10.53.1.10
        port: 7777

scp:
  sbi:
    server:
      - address: 10.53.1.22
        port: 7777
    client:
      nrf:
        - uri: http://10.53.1.10:7777

ausf:
  sbi:
    server:
      - address: 10.53.1.11
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777

udm:
  sbi:
    server:
      - address: 10.53.1.12
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777

pcf:
  sbi:
    server:
      - address: 10.53.1.13
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777
  policy:
    - s_nssai:
        sst: 1
        sd: 1
      qos:
        index: 1
        arp:
          priority_level: 1
          pre_emption_capability: enabled
          pre_emption_vulnerability: enabled
  metrics:
    server:
      - address: 10.53.1.13
        port: 9090

nssf:
  sbi:
    server:
      - address: 10.53.1.14
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777
      nsi:
        - uri: http://10.53.1.10:7777
          s_nssai:
            sst: 1
bsf:
  sbi:
    server:
      - address: 10.53.1.15
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.22:7777

udr:
  sbi:
    server:
      - address: 10.53.1.20
        port: 7777
    client:
      scp:
        - uri: http://10.53.1.2:7777
